AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for the API Service

Parameters:
  Environment:
    Type: String
    Description: "Deployment environment."
  ResourceBaseIdentifier:
    Type: String
    Description: "Base identifier for resource naming."

Resources:
  EarthwatcherApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../api/
      Handler: app.app
      Runtime: python3.9
      Environment:
        Variables:
          ENV: !Ref Environment
          SECRET_NAME: earth-watcher-dev-teller-secrets
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:earth-watcher-dev-teller-secrets-*
      Events:
        EarthwatcherApi:
          Type: Api
          Properties:
            Path: /accounts
            Method: GET
            RestApiId: !Ref ApiGateway

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment

Outputs:
  ApiUrl:
    Description: "URL of the API"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/accounts"
