Resources:
  ExpenzoApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../api/
      Handler: main.handler
      Runtime: python3.9
      Environment:
        Variables:
          ENV: !Ref Environment
          CERT_SECRET_NAME: expenzo-dev-teller-cert
          PK_SECRET_NAME: expenzo-dev-teller-pk
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:expenzo-dev-teller-cert-*
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:expenzo-dev-teller-pk-*
      Events:
        ExpenzoApi:
          Type: Api
          Properties:
            Path: /accounts
            Method: GET
            RestApiId: !Ref ApiGateway
            Auth:
              Authorizer: CognitoAuthorizer
        OptionsMethod:
          Type: Api
          Properties:
            Path: /accounts
            Method: OPTIONS
            RestApiId: !Ref ApiGateway
            Auth:
              Authorizer: NONE
            Cors:
              AllowMethods: "'GET,POST,OPTIONS'"
              AllowHeaders: "'Content-Type,Authorization'"
              AllowOrigin: "'http://localhost:3000'"
              MaxAge: "'600'"
              AllowCredentials: true

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'http://localhost:3000'"
        MaxAge: "'600'"
        AllowCredentials: true
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}
            IdentitySource: "method.request.header.Authorization"
            ValidationExpression: "^Bearer [A-Za-z0-9-_=.]+$"
