AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template with DynamoDB Table for Personal Finance App

Parameters:
  Environment:
    Type: String
    Description: "Deployment environment."
  ResourceBaseIdentifier:
    Type: String
    Description: "Base identifier for resource naming."

Resources:
  ExpenzoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ResourceBaseIdentifier}-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

Outputs:
  ExpenzoTableName:
    Description: "The name of the DynamoDB table."
    Value: !Ref ExpenzoTable
